/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rcs.service.service.base;

import com.liferay.counter.service.CounterLocalService;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.model.PersistedModel;
import com.liferay.portal.service.BaseLocalServiceImpl;
import com.liferay.portal.service.PersistedModelLocalServiceRegistryUtil;
import com.liferay.portal.service.ResourceLocalService;
import com.liferay.portal.service.ResourceService;
import com.liferay.portal.service.UserLocalService;
import com.liferay.portal.service.UserService;
import com.liferay.portal.service.persistence.ResourcePersistence;
import com.liferay.portal.service.persistence.UserPersistence;

import com.rcs.service.model.MessageSource;
import com.rcs.service.service.MessageSourceLocalService;
import com.rcs.service.service.persistence.MessageSourcePK;
import com.rcs.service.service.persistence.MessageSourcePersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * The base implementation of the message source local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.rcs.service.service.impl.MessageSourceLocalServiceImpl}.
 * </p>
 *
 * @author flor
 * @see com.rcs.service.service.impl.MessageSourceLocalServiceImpl
 * @see com.rcs.service.service.MessageSourceLocalServiceUtil
 * @generated
 */
public abstract class MessageSourceLocalServiceBaseImpl
	extends BaseLocalServiceImpl implements MessageSourceLocalService,
		IdentifiableBean {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.rcs.service.service.MessageSourceLocalServiceUtil} to access the message source local service.
	 */

	/**
	 * Adds the message source to the database. Also notifies the appropriate model listeners.
	 *
	 * @param messageSource the message source
	 * @return the message source that was added
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	public MessageSource addMessageSource(MessageSource messageSource)
		throws SystemException {
		messageSource.setNew(true);

		return messageSourcePersistence.update(messageSource, false);
	}

	/**
	 * Creates a new message source with the primary key. Does not add the message source to the database.
	 *
	 * @param messageSourcePK the primary key for the new message source
	 * @return the new message source
	 */
	public MessageSource createMessageSource(MessageSourcePK messageSourcePK) {
		return messageSourcePersistence.create(messageSourcePK);
	}

	/**
	 * Deletes the message source with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param messageSourcePK the primary key of the message source
	 * @return the message source that was removed
	 * @throws PortalException if a message source with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.DELETE)
	public MessageSource deleteMessageSource(MessageSourcePK messageSourcePK)
		throws PortalException, SystemException {
		return messageSourcePersistence.remove(messageSourcePK);
	}

	/**
	 * Deletes the message source from the database. Also notifies the appropriate model listeners.
	 *
	 * @param messageSource the message source
	 * @return the message source that was removed
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.DELETE)
	public MessageSource deleteMessageSource(MessageSource messageSource)
		throws SystemException {
		return messageSourcePersistence.remove(messageSource);
	}

	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(MessageSource.class,
			clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery)
		throws SystemException {
		return messageSourcePersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end)
		throws SystemException {
		return messageSourcePersistence.findWithDynamicQuery(dynamicQuery,
			start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator orderByComparator) throws SystemException {
		return messageSourcePersistence.findWithDynamicQuery(dynamicQuery,
			start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows that match the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows that match the dynamic query
	 * @throws SystemException if a system exception occurred
	 */
	public long dynamicQueryCount(DynamicQuery dynamicQuery)
		throws SystemException {
		return messageSourcePersistence.countWithDynamicQuery(dynamicQuery);
	}

	public MessageSource fetchMessageSource(MessageSourcePK messageSourcePK)
		throws SystemException {
		return messageSourcePersistence.fetchByPrimaryKey(messageSourcePK);
	}

	/**
	 * Returns the message source with the primary key.
	 *
	 * @param messageSourcePK the primary key of the message source
	 * @return the message source
	 * @throws PortalException if a message source with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	public MessageSource getMessageSource(MessageSourcePK messageSourcePK)
		throws PortalException, SystemException {
		return messageSourcePersistence.findByPrimaryKey(messageSourcePK);
	}

	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException, SystemException {
		return messageSourcePersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the message sources.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param start the lower bound of the range of message sources
	 * @param end the upper bound of the range of message sources (not inclusive)
	 * @return the range of message sources
	 * @throws SystemException if a system exception occurred
	 */
	public List<MessageSource> getMessageSources(int start, int end)
		throws SystemException {
		return messageSourcePersistence.findAll(start, end);
	}

	/**
	 * Returns the number of message sources.
	 *
	 * @return the number of message sources
	 * @throws SystemException if a system exception occurred
	 */
	public int getMessageSourcesCount() throws SystemException {
		return messageSourcePersistence.countAll();
	}

	/**
	 * Updates the message source in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param messageSource the message source
	 * @return the message source that was updated
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	public MessageSource updateMessageSource(MessageSource messageSource)
		throws SystemException {
		return updateMessageSource(messageSource, true);
	}

	/**
	 * Updates the message source in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param messageSource the message source
	 * @param merge whether to merge the message source with the current session. See {@link com.liferay.portal.service.persistence.BatchSession#update(com.liferay.portal.kernel.dao.orm.Session, com.liferay.portal.model.BaseModel, boolean)} for an explanation.
	 * @return the message source that was updated
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	public MessageSource updateMessageSource(MessageSource messageSource,
		boolean merge) throws SystemException {
		messageSource.setNew(false);

		return messageSourcePersistence.update(messageSource, merge);
	}

	/**
	 * Returns the message source local service.
	 *
	 * @return the message source local service
	 */
	public MessageSourceLocalService getMessageSourceLocalService() {
		return messageSourceLocalService;
	}

	/**
	 * Sets the message source local service.
	 *
	 * @param messageSourceLocalService the message source local service
	 */
	public void setMessageSourceLocalService(
		MessageSourceLocalService messageSourceLocalService) {
		this.messageSourceLocalService = messageSourceLocalService;
	}

	/**
	 * Returns the message source persistence.
	 *
	 * @return the message source persistence
	 */
	public MessageSourcePersistence getMessageSourcePersistence() {
		return messageSourcePersistence;
	}

	/**
	 * Sets the message source persistence.
	 *
	 * @param messageSourcePersistence the message source persistence
	 */
	public void setMessageSourcePersistence(
		MessageSourcePersistence messageSourcePersistence) {
		this.messageSourcePersistence = messageSourcePersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the resource remote service.
	 *
	 * @return the resource remote service
	 */
	public ResourceService getResourceService() {
		return resourceService;
	}

	/**
	 * Sets the resource remote service.
	 *
	 * @param resourceService the resource remote service
	 */
	public void setResourceService(ResourceService resourceService) {
		this.resourceService = resourceService;
	}

	/**
	 * Returns the resource persistence.
	 *
	 * @return the resource persistence
	 */
	public ResourcePersistence getResourcePersistence() {
		return resourcePersistence;
	}

	/**
	 * Sets the resource persistence.
	 *
	 * @param resourcePersistence the resource persistence
	 */
	public void setResourcePersistence(ResourcePersistence resourcePersistence) {
		this.resourcePersistence = resourcePersistence;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		PersistedModelLocalServiceRegistryUtil.register("com.rcs.service.model.MessageSource",
			messageSourceLocalService);
	}

	public void destroy() {
		PersistedModelLocalServiceRegistryUtil.unregister(
			"com.rcs.service.model.MessageSource");
	}

	/**
	 * Returns the Spring bean ID for this bean.
	 *
	 * @return the Spring bean ID for this bean
	 */
	public String getBeanIdentifier() {
		return _beanIdentifier;
	}

	/**
	 * Sets the Spring bean ID for this bean.
	 *
	 * @param beanIdentifier the Spring bean ID for this bean
	 */
	public void setBeanIdentifier(String beanIdentifier) {
		_beanIdentifier = beanIdentifier;
	}

	public Object invokeMethod(String name, String[] parameterTypes,
		Object[] arguments) throws Throwable {
		return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
	}

	protected Class<?> getModelClass() {
		return MessageSource.class;
	}

	protected String getModelClassName() {
		return MessageSource.class.getName();
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = messageSourcePersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = MessageSourceLocalService.class)
	protected MessageSourceLocalService messageSourceLocalService;
	@BeanReference(type = MessageSourcePersistence.class)
	protected MessageSourcePersistence messageSourcePersistence;
	@BeanReference(type = CounterLocalService.class)
	protected CounterLocalService counterLocalService;
	@BeanReference(type = ResourceLocalService.class)
	protected ResourceLocalService resourceLocalService;
	@BeanReference(type = ResourceService.class)
	protected ResourceService resourceService;
	@BeanReference(type = ResourcePersistence.class)
	protected ResourcePersistence resourcePersistence;
	@BeanReference(type = UserLocalService.class)
	protected UserLocalService userLocalService;
	@BeanReference(type = UserService.class)
	protected UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	private String _beanIdentifier;
	private MessageSourceLocalServiceClpInvoker _clpInvoker = new MessageSourceLocalServiceClpInvoker();
}